name: Install Issue
description: Report problems installing YouJust
title: "[Install Issue]: "
labels: ["install issue"]

body:
  - type: input
    id: os
    attributes:
      label: Linux Distro
      placeholder: "Example: Linux Mint 22.3, Ubuntu 26.04"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: YouJust Version
      placeholder: "Example: v1.0.0"

  - type: textarea
    id: problem
    attributes:
      label: Installation Problem
      description: Describe what happens when installing the game.
      placeholder: "Example: Installation fails, app does not appear, permission error..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Download...
        2. Open installer/package...
        3. See error
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message or Logs
      description: Paste any error messages here.
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: Add screenshots or recordings if they help explain the issue.

  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      options:
        - label: I downloaded YouJust from an official source (Github Releases).
          required: true
        - label: I confirmed my distro supports YouJust.
          required: true
        - label: I checked existing issues and confirmed this installation issue has not already been reported.
          required: true
